services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "9200:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: yarn dev
    profiles:
      - dev

  # Production service
  app:
    image: obscreen/webtoys:latest
    ports:
      - "9100:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    profiles:
      - prod
