name: Build Docker

on:
  push:
    branches:
      - master
    paths:
      - 'version.txt'
      - 'enforce.txt'
  workflow_dispatch:
    
jobs:
  webtoys:
    name: Build Webtoys
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_OBSCREEN_USERNAME }}
          password: ${{ secrets.DOCKER_OBSCREEN_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "obscreen/ob-builder"
          install: true
      - name: Build and push app
        uses: docker/build-push-action@v6
        with:
          tags: "${{ secrets.DOCKER_OBSCREEN_USERNAME }}/webtoys:latest"
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
          context: .
          file: ./Dockerfile

  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: [webtoys]
    steps:
      - name: Make deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          port: ${{ secrets.JRKX_PORT }}
          username: ${{ secrets.JRKX_USERNAME }}
          host: ${{ secrets.JRKX_HOST }}
          key: ${{ secrets.JRKX_GITHUB_PKEY }}
          script: cd ~/webtoys/ ; git pull ;docker compose --profile prod pull app; docker compose --profile prod down app; docker compose --profile prod up -d app

  send-slack-failure-notification:
    name: Failure Notification
    needs: [ deploy-production ]
    if: ${{ failure() }}
    secrets: inherit
    uses: obscreen/infrastructure/.github/workflows/slack-state-notification.yaml@master
    with:
      state: failure
      project-name: "webtoys"
      extra-message: "${{ github.event.repository.name }} - `${{ github.event.head_commit.message }}` on `${{ github.ref_name }}`"

  send-slack-success-notification:
    name: Success Notification
    needs: [ deploy-production ]
    if: ${{ success() }}
    secrets: inherit
    uses: obscreen/infrastructure/.github/workflows/slack-state-notification.yaml@master
    with:
      state: success
      project-name: "webtoys"
      extra-message: "${{ github.event.repository.name }} - `${{ github.event.head_commit.message }}` on `${{ github.ref_name }}`"

